// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2014.1
// Copyright (C) 2014 Xilinx Inc. All rights reserved.
// 
// ==============================================================

#ifndef __linux__

#include "xstatus.h"
#include "xparameters.h"
#include "xrunqueue.h"

extern XRunqueue_Config XRunqueue_ConfigTable[];

XRunqueue_Config *XRunqueue_LookupConfig(u16 DeviceId) {
	XRunqueue_Config *ConfigPtr = NULL;

	int Index;

	for (Index = 0; Index < XPAR_XRUNQUEUE_NUM_INSTANCES; Index++) {
		if (XRunqueue_ConfigTable[Index].DeviceId == DeviceId) {
			ConfigPtr = &XRunqueue_ConfigTable[Index];
			break;
		}
	}

	return ConfigPtr;
}

int XRunqueue_Initialize(XRunqueue *InstancePtr, u16 DeviceId) {
	XRunqueue_Config *ConfigPtr;

	Xil_AssertNonvoid(InstancePtr != NULL);

	ConfigPtr = XRunqueue_LookupConfig(DeviceId);
	if (ConfigPtr == NULL) {
		InstancePtr->IsReady = 0;
		return (XST_DEVICE_NOT_FOUND);
	}

	return XRunqueue_CfgInitialize(InstancePtr, ConfigPtr);
}

#endif

